apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-artifactless-two
  namespace: testing-new-namespaces
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      app: nginx-artifactless-two
  template:
    metadata:
      labels:
        app: nginx-artifactless-two
    spec:
      containers:
        - name: nginx-artifactless-two
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "test"
