apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-artifactless-two-ingress
  namespace: testing-new-namespaces
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx-artifactless-two.home.coolkev.com
spec:
  ingressClassName: traefik
  rules:
  - host: nginx-artifactless-two.home.coolkev.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-artifactless-two-service
            port:
              name: http
