apiVersion: v1
kind: Service
metadata:
  name: nginx-artifactless-two-service
  namespace: testing-new-namespaces
spec:
  type: LoadBalancer
  selector:
    app: nginx-artifactless-two
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
