apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-artifactless
  namespace: test
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: nginx-artifactless
  template:
    metadata:
      labels:
        app: nginx-artifactless
    spec:
      containers:
        - name: nginx-artifactless
          image: nginx:latest
          ports:
            - containerPort: 80
